# Generated by Django 5.0 on 2024-01-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
    ]
