# Generated by Django 5.0 on 2024-01-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20240103_2118'),
    ]

    operations = [
    ]
