# Generated by Django 5.0 on 2024-01-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_profile_password'),
    ]

    operations = [
    ]
