# Generated by Django 5.0 on 2024-01-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customlogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomLogEntry',
        ),
    ]
