# Generated by Django 5.0 on 2024-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_consumer_consumer_id_alter_consumer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='consumer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
