# Generated by Django 5.0 on 2024-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_consumer_consumer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
