# Generated by Django 5.0 on 2024-02-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_consumer_otp_consumer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
