# Generated by Django 5.0 on 2024-03-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_ownerprofile_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
