# Generated by Django 5.0 on 2024-03-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_userprofile_user_delete_ownerprofile_and_more'),
    ]

    operations = [
    ]
